server:
  port: 8888
#  address: 172.16.225.99
spring:
  application:
    name: config-server
  # config svn
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: svn://172.16.225.98/repositories/service-config/
          username: admin
          password: 4880300
#          uri: https://pc-20131011xrrb/svn/service-config/
#          username: tkdiooo
#          password: 4880300
        # config git
#        git:
#          uri: https://github.com/tkdiooo/config.git
#          search-paths: config

logback:
  file:
    space: /opt/logback