eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10002/eureka/
server:
  port: 8765
spring:
  application:
    name: cloud-feign
  zipkin:
    base-url: http://localhost:8769
##开启feign开关
feign:
  hystrix:
    enabled: true