eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10002/eureka/
server:
  port: 8763
spring:
  application:
    name: cloud-client
  zipkin:
    base-url: http://localhost:8769
logging:
  path: D:/opt/logs
