#spring mvc setting
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # 指定静态资源处理路径，如果是默认/**，404请求不会抛出NoHandlerFoundException
    static-path-pattern: /static/**
#jsp development setting
server:
  jsp-servlet:
    init-parameters:
      development: true