#spring mvc setting
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # 指定静态资源处理路径，如果是默认/**，404请求不会抛出NoHandlerFoundException
    static-path-pattern: /static/**
#jsp development setting
server:
  port: 8081
  address: localhost
  contextPath: /jspdemo
  tomcat:
    uri-encoding: utf-8
  jsp-servlet:
    init-parameters:
      development: true
#common setting
website:
  static:
    resources: http://localhost:8080/static-resources

#spring.cloud.config
#--spring.cloud.config.name=jsp
#--spring.cloud.config.profile=deve
#--spring.cloud.config.label=config
#--spring.cloud.config.uri=http://localhost:8888