#server setting
server:
  port: 8081
  address: localhost
  context-path: /jspdemo
  tomcat:
    uri-encoding: utf-8
  context-parameters:
    logback-config-location: http://localhost:8888/logback/framework/jsp
    logback-expose-webapp-root: true
  soa: true
#spring mvc setting
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # 指定静态资源处理路径
    static-path-pattern: /static/**
  redis:
      host-name: 172.16.225.98
      port: 6379
      password: redis123
      pool:
        max-total: 300
        max-wait-millis: 10000
        max-idle: 100
        min-idle: 50
#jsp development setting
  jsp-servlet:
    init-parameters:
      development: true
#logging setting
logging:
  file: D:\opt\logs\test.log
  level: error
#common setting
website:
  # 网站支持
  support:
    # 静态资源服务
    static-resources: http://localhost:8080/static-resources
  # 网站请求
  request:
    # 排除映射
    exclude-mapping: /, /index.html, *.jsp
#dubbo setting
dubbo:
  application:
    #服务消费名称信息
    name: dubbo_consumer
    #日志适配
    logger: slf4j
  registry:
    #zookeeper注册中心服务地址
    address: zookeeper://172.16.225.98:2181
    #注册中心不存在时，是否报错
    check: false
    #是否向此注册中心注册服务，如果设为false，将只订阅，不注册
    register: true
    #是否向此注册中心订阅服务，如果设为false，将只注册，不订阅
    subscribe: true
    #注册中心请求超时时间(毫秒)
    timeout: 2000

#spring.cloud.config
#--spring.cloud.config.name=jsp
#--spring.cloud.config.profile=deve
#--spring.cloud.config.label=config
#--spring.cloud.config.uri=http://localhost:8888