server:
  port: 8888
spring:
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: https://pc-20131011xrrb/svn/service-config/
          username: tkdiooo
          password: 4880300